#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPLek.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HWTicket")]
	public partial class DB_LEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMAS_APPROVE(MAS_APPROVE instance);
    partial void UpdateMAS_APPROVE(MAS_APPROVE instance);
    partial void DeleteMAS_APPROVE(MAS_APPROVE instance);
    partial void InsertMAS_DOC(MAS_DOC instance);
    partial void UpdateMAS_DOC(MAS_DOC instance);
    partial void DeleteMAS_DOC(MAS_DOC instance);
    partial void InsertMAS_SS(MAS_SS instance);
    partial void UpdateMAS_SS(MAS_SS instance);
    partial void DeleteMAS_SS(MAS_SS instance);
    partial void InsertTASK_SUB(TASK_SUB instance);
    partial void UpdateTASK_SUB(TASK_SUB instance);
    partial void DeleteTASK_SUB(TASK_SUB instance);
    partial void InsertTASK_MAIN(TASK_MAIN instance);
    partial void UpdateTASK_MAIN(TASK_MAIN instance);
    partial void DeleteTASK_MAIN(TASK_MAIN instance);
    #endregion
		
		public DB_LEDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HWTicketConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_LEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_LEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_LEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_LEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAS_APPROVE> MAS_APPROVEs
		{
			get
			{
				return this.GetTable<MAS_APPROVE>();
			}
		}
		
		public System.Data.Linq.Table<MAS_DOC> MAS_DOCs
		{
			get
			{
				return this.GetTable<MAS_DOC>();
			}
		}
		
		public System.Data.Linq.Table<MAS_SS> MAS_SSes
		{
			get
			{
				return this.GetTable<MAS_SS>();
			}
		}
		
		public System.Data.Linq.Table<TASK_SUB> TASK_SUBs
		{
			get
			{
				return this.GetTable<TASK_SUB>();
			}
		}
		
		public System.Data.Linq.Table<TASK_MAIN> TASK_MAINs
		{
			get
			{
				return this.GetTable<TASK_MAIN>();
			}
		}
		
		public System.Data.Linq.Table<VW_TICKET> VW_TICKETs
		{
			get
			{
				return this.GetTable<VW_TICKET>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_APPROVE")]
	public partial class MAS_APPROVE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _APPROVE_ID;
		
		private string _APPROVE_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAPPROVE_IDChanging(int value);
    partial void OnAPPROVE_IDChanged();
    partial void OnAPPROVE_NAMEChanging(string value);
    partial void OnAPPROVE_NAMEChanged();
    #endregion
		
		public MAS_APPROVE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int APPROVE_ID
		{
			get
			{
				return this._APPROVE_ID;
			}
			set
			{
				if ((this._APPROVE_ID != value))
				{
					this.OnAPPROVE_IDChanging(value);
					this.SendPropertyChanging();
					this._APPROVE_ID = value;
					this.SendPropertyChanged("APPROVE_ID");
					this.OnAPPROVE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_NAME", DbType="VarChar(50)")]
		public string APPROVE_NAME
		{
			get
			{
				return this._APPROVE_NAME;
			}
			set
			{
				if ((this._APPROVE_NAME != value))
				{
					this.OnAPPROVE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._APPROVE_NAME = value;
					this.SendPropertyChanged("APPROVE_NAME");
					this.OnAPPROVE_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_DOC")]
	public partial class MAS_DOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DOC_ID;
		
		private string _DOC_NAME;
		
		private string _TYPE;
		
		private string _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOC_IDChanging(int value);
    partial void OnDOC_IDChanged();
    partial void OnDOC_NAMEChanging(string value);
    partial void OnDOC_NAMEChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnFLAGChanging(string value);
    partial void OnFLAGChanged();
    #endregion
		
		public MAS_DOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DOC_ID
		{
			get
			{
				return this._DOC_ID;
			}
			set
			{
				if ((this._DOC_ID != value))
				{
					this.OnDOC_IDChanging(value);
					this.SendPropertyChanging();
					this._DOC_ID = value;
					this.SendPropertyChanged("DOC_ID");
					this.OnDOC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_NAME", DbType="VarChar(100)")]
		public string DOC_NAME
		{
			get
			{
				return this._DOC_NAME;
			}
			set
			{
				if ((this._DOC_NAME != value))
				{
					this.OnDOC_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DOC_NAME = value;
					this.SendPropertyChanged("DOC_NAME");
					this.OnDOC_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(1)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(1)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_SS")]
	public partial class MAS_SS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SS_ID;
		
		private string _SS_NAME;
		
		private string _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSS_IDChanging(int value);
    partial void OnSS_IDChanged();
    partial void OnSS_NAMEChanging(string value);
    partial void OnSS_NAMEChanged();
    partial void OnFLAGChanging(string value);
    partial void OnFLAGChanged();
    #endregion
		
		public MAS_SS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SS_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SS_ID
		{
			get
			{
				return this._SS_ID;
			}
			set
			{
				if ((this._SS_ID != value))
				{
					this.OnSS_IDChanging(value);
					this.SendPropertyChanging();
					this._SS_ID = value;
					this.SendPropertyChanged("SS_ID");
					this.OnSS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SS_NAME", DbType="VarChar(30)")]
		public string SS_NAME
		{
			get
			{
				return this._SS_NAME;
			}
			set
			{
				if ((this._SS_NAME != value))
				{
					this.OnSS_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SS_NAME = value;
					this.SendPropertyChanged("SS_NAME");
					this.OnSS_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(1)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TASK_SUB")]
	public partial class TASK_SUB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LE_ID;
		
		private int _DOC_ID;
		
		private string _DETAIL_SUB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLE_IDChanging(int value);
    partial void OnLE_IDChanged();
    partial void OnDOC_IDChanging(int value);
    partial void OnDOC_IDChanged();
    partial void OnDETAIL_SUBChanging(string value);
    partial void OnDETAIL_SUBChanged();
    #endregion
		
		public TASK_SUB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LE_ID
		{
			get
			{
				return this._LE_ID;
			}
			set
			{
				if ((this._LE_ID != value))
				{
					this.OnLE_IDChanging(value);
					this.SendPropertyChanging();
					this._LE_ID = value;
					this.SendPropertyChanged("LE_ID");
					this.OnLE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DOC_ID
		{
			get
			{
				return this._DOC_ID;
			}
			set
			{
				if ((this._DOC_ID != value))
				{
					this.OnDOC_IDChanging(value);
					this.SendPropertyChanging();
					this._DOC_ID = value;
					this.SendPropertyChanged("DOC_ID");
					this.OnDOC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAIL_SUB", DbType="VarChar(50)")]
		public string DETAIL_SUB
		{
			get
			{
				return this._DETAIL_SUB;
			}
			set
			{
				if ((this._DETAIL_SUB != value))
				{
					this.OnDETAIL_SUBChanging(value);
					this.SendPropertyChanging();
					this._DETAIL_SUB = value;
					this.SendPropertyChanged("DETAIL_SUB");
					this.OnDETAIL_SUBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TASK_MAIN")]
	public partial class TASK_MAIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TICKETNO;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATECODE;
		
		private string _TITLE;
		
		private string _DETAIL;
		
		private System.Nullable<System.DateTime> _S_DATE;
		
		private System.Nullable<System.DateTime> _E_DATE;
		
		private System.Nullable<System.DateTime> _F_DATE;
		
		private string _STCODE;
		
		private string _STATUS;
		
		private string _CLOSECODE;
		
		private System.Nullable<System.DateTime> _CLOSEDATE;
		
		private string _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTICKETNOChanging(string value);
    partial void OnTICKETNOChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnCREATECODEChanging(string value);
    partial void OnCREATECODEChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnDETAILChanging(string value);
    partial void OnDETAILChanged();
    partial void OnS_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnS_DATEChanged();
    partial void OnE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_DATEChanged();
    partial void OnF_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnF_DATEChanged();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnCLOSECODEChanging(string value);
    partial void OnCLOSECODEChanged();
    partial void OnCLOSEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCLOSEDATEChanged();
    partial void OnFLAGChanging(string value);
    partial void OnFLAGChanged();
    #endregion
		
		public TASK_MAIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TICKETNO", DbType="VarChar(20)")]
		public string TICKETNO
		{
			get
			{
				return this._TICKETNO;
			}
			set
			{
				if ((this._TICKETNO != value))
				{
					this.OnTICKETNOChanging(value);
					this.SendPropertyChanging();
					this._TICKETNO = value;
					this.SendPropertyChanged("TICKETNO");
					this.OnTICKETNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATECODE", DbType="VarChar(50)")]
		public string CREATECODE
		{
			get
			{
				return this._CREATECODE;
			}
			set
			{
				if ((this._CREATECODE != value))
				{
					this.OnCREATECODEChanging(value);
					this.SendPropertyChanging();
					this._CREATECODE = value;
					this.SendPropertyChanged("CREATECODE");
					this.OnCREATECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(100)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAIL", DbType="VarChar(MAX)")]
		public string DETAIL
		{
			get
			{
				return this._DETAIL;
			}
			set
			{
				if ((this._DETAIL != value))
				{
					this.OnDETAILChanging(value);
					this.SendPropertyChanging();
					this._DETAIL = value;
					this.SendPropertyChanged("DETAIL");
					this.OnDETAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> S_DATE
		{
			get
			{
				return this._S_DATE;
			}
			set
			{
				if ((this._S_DATE != value))
				{
					this.OnS_DATEChanging(value);
					this.SendPropertyChanging();
					this._S_DATE = value;
					this.SendPropertyChanged("S_DATE");
					this.OnS_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> E_DATE
		{
			get
			{
				return this._E_DATE;
			}
			set
			{
				if ((this._E_DATE != value))
				{
					this.OnE_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_DATE = value;
					this.SendPropertyChanged("E_DATE");
					this.OnE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> F_DATE
		{
			get
			{
				return this._F_DATE;
			}
			set
			{
				if ((this._F_DATE != value))
				{
					this.OnF_DATEChanging(value);
					this.SendPropertyChanging();
					this._F_DATE = value;
					this.SendPropertyChanged("F_DATE");
					this.OnF_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5)")]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(1)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSECODE", DbType="VarChar(50)")]
		public string CLOSECODE
		{
			get
			{
				return this._CLOSECODE;
			}
			set
			{
				if ((this._CLOSECODE != value))
				{
					this.OnCLOSECODEChanging(value);
					this.SendPropertyChanging();
					this._CLOSECODE = value;
					this.SendPropertyChanged("CLOSECODE");
					this.OnCLOSECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CLOSEDATE
		{
			get
			{
				return this._CLOSEDATE;
			}
			set
			{
				if ((this._CLOSEDATE != value))
				{
					this.OnCLOSEDATEChanging(value);
					this.SendPropertyChanging();
					this._CLOSEDATE = value;
					this.SendPropertyChanged("CLOSEDATE");
					this.OnCLOSEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(1)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_TICKET")]
	public partial class VW_TICKET
	{
		
		private int _ID;
		
		private string _TITLE;
		
		private string _TICKETNO;
		
		private string _DETAIL;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATENAME;
		
		private string _STCODE;
		
		private string _FNAME;
		
		private string _LNAME;
		
		private string _Recieve;
		
		private string _DPCODE;
		
		private string _SS_NAME;
		
		private string _STATUS;
		
		private string _FLAG;
		
		private string _CLOSECODE;
		
		private System.Nullable<System.DateTime> _CLOSEDATE;
		
		private System.Nullable<System.DateTime> _S_DATE;
		
		private System.Nullable<System.DateTime> _E_DATE;
		
		private System.Nullable<System.DateTime> _F_DATE;
		
		public VW_TICKET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(100)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this._TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TICKETNO", DbType="VarChar(20)")]
		public string TICKETNO
		{
			get
			{
				return this._TICKETNO;
			}
			set
			{
				if ((this._TICKETNO != value))
				{
					this._TICKETNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAIL", DbType="VarChar(MAX)")]
		public string DETAIL
		{
			get
			{
				return this._DETAIL;
			}
			set
			{
				if ((this._DETAIL != value))
				{
					this._DETAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this._CREATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATENAME", DbType="VarChar(50)")]
		public string CREATENAME
		{
			get
			{
				return this._CREATENAME;
			}
			set
			{
				if ((this._CREATENAME != value))
				{
					this._CREATENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5)")]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this._STCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="VarChar(50)")]
		public string FNAME
		{
			get
			{
				return this._FNAME;
			}
			set
			{
				if ((this._FNAME != value))
				{
					this._FNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNAME", DbType="VarChar(50)")]
		public string LNAME
		{
			get
			{
				return this._LNAME;
			}
			set
			{
				if ((this._LNAME != value))
				{
					this._LNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recieve", DbType="VarChar(50)")]
		public string Recieve
		{
			get
			{
				return this._Recieve;
			}
			set
			{
				if ((this._Recieve != value))
				{
					this._Recieve = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPCODE", DbType="NVarChar(10)")]
		public string DPCODE
		{
			get
			{
				return this._DPCODE;
			}
			set
			{
				if ((this._DPCODE != value))
				{
					this._DPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SS_NAME", DbType="VarChar(30)")]
		public string SS_NAME
		{
			get
			{
				return this._SS_NAME;
			}
			set
			{
				if ((this._SS_NAME != value))
				{
					this._SS_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(1)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(1)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSECODE", DbType="VarChar(50)")]
		public string CLOSECODE
		{
			get
			{
				return this._CLOSECODE;
			}
			set
			{
				if ((this._CLOSECODE != value))
				{
					this._CLOSECODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CLOSEDATE
		{
			get
			{
				return this._CLOSEDATE;
			}
			set
			{
				if ((this._CLOSEDATE != value))
				{
					this._CLOSEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> S_DATE
		{
			get
			{
				return this._S_DATE;
			}
			set
			{
				if ((this._S_DATE != value))
				{
					this._S_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> E_DATE
		{
			get
			{
				return this._E_DATE;
			}
			set
			{
				if ((this._E_DATE != value))
				{
					this._E_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> F_DATE
		{
			get
			{
				return this._F_DATE;
			}
			set
			{
				if ((this._F_DATE != value))
				{
					this._F_DATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
